[package]
name = "multithread_raycaster_game"
version = "0.3.0"
edition = "2021"

[dependencies]
winit = "0.30"
softbuffer = "0.4"
clap = {version = "4.5", features = ["cargo"]}
glam = {version = "0.28", features = ["fast-math", "rkyv", "bytecheck"]}
rkyv = {version = "0.7"}
nalgebra = {version = "0.32", features = ["rkyv-serialize", "mint"]}
mint = {version= "0.5"}
rayon = {version = "1.10"}
ahash = {version = "0.8"}
parking_lot = "0.12"
[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
codspeed-criterion-compat = {version = "2.6", features = ["html_reports"]}
iai = "0.1"
[[bench]]
name = "svo"
harness = false
