name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@master

      - name: Set up dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev pkg-config libudev-dev
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Build (Ubuntu)
        if: runner.os == 'Linux'
        run: cargo build --release --target=${{ matrix.target }}

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cargo build --release --target=${{ matrix.target }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./target/${{ matrix.target }}/release/myapp
          asset_name: myapp-${{ matrix.target }}
          asset_content_type: application/octet-stream
