name: Release

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build -t multithread_raycaster_game .

      - name: Run Docker container
        run: docker run --name multithread_raycaster_game multithread_raycaster_game

      - name: Copy binary from Docker container
        if: runner.os == 'Linux'
        run: docker cp multithread_raycaster_game:/usr/src/multithread_raycaster_game/target/release/multithread_raycaster_game .

      - name: Copy binary from Docker container (Windows)
        if: runner.os == 'Windows'
        run: docker cp multithread_raycaster_game:/usr/src/multithread_raycaster_game/target/release/multithread_raycaster_game.exe .

      - name: Upload Release Asset (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./multithread_raycaster_game
          asset_name: multithread_raycaster_game
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./multithread_raycaster_game.exe
          asset_name: multithread_raycaster_game.exe
          asset_content_type: application/octet-stream
